name: car_wazz
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.10.4


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4
  google_fonts: ^8.0.1
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/launcher_icon.png"
  adaptive_icon_foreground: "assets/carwazz_foreground.png"
  adaptive_icon_background: "assets/carwazz_background.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
  
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash_logo.png
  android: true
  ios: true

  android_12:
    image: assets/splash_logo.png
    color: "#FFFFFF"